# Use an official Python runtime as a base image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy requirements file into the image
COPY back_end_requirements.txt ./requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Flask app code into the container
COPY ./back_end .

# Expose the port Flask will run on
EXPOSE 5000

# Define the command to run the app
CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]